### ISSUE TITLE
Bug: collaboration server sometimes crashes when adding a subfeature

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo3#219]
@kyostiebi to attach error message as comment here

**Comment by kyostiebi** [comment]
The error always occurs after "temporary documents" have been updated:
[Nest] 57707  - 05/25/2023, 11:11:21 AM   DEBUG [ChangesService] *** TEMPORARY DATA INSERTTED ***
[Nest] 57707  - 05/25/2023, 11:11:21 AM   DEBUG [ChangesService] Updates "temporary document" -status --> "valid" -status

/Users/kyosti/src/Apollo/jbrowse-plugin-apollo/.yarn/cache/mongodb-npm-4.7.0-d0a46888e7-6c8ddf1d14.zip/node_modules/mongodb/src/cmap/connection.ts:450
          callback(new MongoServerError(document));
                   ^
MongoServerError: Transaction 15 has been committed.
    at Connection.onMessage (/Users/kyosti/src/Apollo/jbrowse-plugin-apollo/.yarn/cache/mongodb-npm-4.7.0-d0a46888e7-6c8ddf1d14.zip/node_modules/mongodb/src/cmap/connection.ts:450:20)
    at MessageStream.<anonymous> (/Users/kyosti/src/Apollo/jbrowse-plugin-apollo/.yarn/cache/mongodb-npm-4.7.0-d0a46888e7-6c8ddf1d14.zip/node_modules/mongodb/src/cmap/connection.ts:268:56)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (/Users/kyosti/src/Apollo/jbrowse-plugin-apollo/.yarn/cache/mongodb-npm-4.7.0-d0a46888e7-6c8ddf1d14.zip/node_modules/mongodb/src/cmap/message_stream.ts:194:14)
    at MessageStream._write (/Users/kyosti/src/Apollo/jbrowse-plugin-apollo/.yarn/cache/mongodb-npm-4.7.0-d0a46888e7-6c8ddf1d14.zip/node_modules/mongodb/src/cmap/message_stream.ts:71:5)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:390:28)

**Comment by kyostiebi** [comment]
In addition to the fix that I just pushed to _Issue219_random_crash_when_adding_subfeature_ -branch, we can also set _maxTransactionLockRequestTimeoutMillis_ parameter in _mongo.conf_. The default value for _maxTransactionLockRequestTimeoutMillis_ -parameter is only 5ms that may not be enough in all cases.

 _setParameter:
  maxTransactionLockRequestTimeoutMillis: 2000_
